### PR TITLE
fix

### PR DESCRIPTION
**Pull request by wael444**
+ 'git' is needed as a dependency, when for most users they would know this already, as they are executing scripts from a git repository; especially if its linux users that know what they are doing.
+ there is no explanation for why and what the scripts do.
+ they assume OneShot is installed in one directory.
+ not everyone has bash.
+ `onejournal` script is superceded by simply going to the game directory and launching the `./journal` script.
+ mode `0755` (executable bit) is not set on the scripts, when git supports that.
+ checking on the 'backup' is not needed.
+ running a seperate final program inside a script should be `exec`, as in that point it is no longer a process child.
+ this entire repository is overkill, and is superceded by *one* command or 3 lines of shell script. a simpler way of doing this was to contribute to the OneShot Discord server and telling them the appropriate fixes and information.

### CODE REVIEW

**Comment by wael444** [comment]
this repository is a clone of the discord thread https://discord.com/channels/256926147827335170/1043913636537696356/1043914823198584922, when you or others can link users to this thread.

**Comment by Mizosu97** [comment]
> 

i made this because somebody didnt know what to do, even with following the thread

**Comment by wael444** [comment]
> i made this because somebody didnt know what to do, even with following the thread

this repository IS that thread??

**Comment by Mizosu97** [comment]
Your little "fix" isn't even a fix. It does not fix oneshot.

I don't understand why you think I'm not allowed to create a program based on a discord thread. 

Stop commenting on all of my repos because there's one tiny thing you don't like. I have told you this MANY times before, yet you keep doing it. If there's something you don't like, then shut up and deal with it.

**Comment by wael444** [comment]
> Stop commenting on all of my repos

as of GitHub, i have only did this repository and the 'mgpu' utility. i have not said a word about the following:

+ [akali](https://github.com/Mizosu97/akali)
+ [i3rice](https://github.com/Mizosu97/i3rice)
+ [osirus](https://github.com/Mizosu97/osirus)
+ [Mizosu97](https://github.com/Mizosu97/Mizosu97)
+ [mizos_iso](https://github.com/Mizosu97/mizos_iso)
+ [mizinstall](https://github.com/Mizosu97/mizinstall)
+ [prizm](https://github.com/Mizosu97/prizm)
>> Stop commenting on all of my repos because there's one tiny thing you don't like. I have told you this MANY times before, yet you keep doing it. If there's something you don't like, then shut up and deal with it.
  + your horrible ability to:
    + face your terrible decisions
    + learn something new
    + take criticism
  
> I don't understand why you think I'm not allowed to create a program based on a discord thread.

it is not a program; it is a bash script that does the exact same actions provided by the Discord thread.

**Pull request closed without merging**
